name: Push Docker image to github

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        run: |
          docker login --username PRASUN-SITAULA --password ${{ secrets.GH_TOKEN }} ghcr.io
          docker build -t ghcr.io/prasun-sitaula/major-website:latest .
          docker push ghcr.io/prasun-sitaula/major-website:latest
